
language: java

jdk: oraclejdk11

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - aljasones@yandex.ru
    on_failure: never
    on_success: never